name: melos_app

packages:
  - "packages/core/**"
  - "packages/feature/**"
  - app
  - backend


command:
  bootstrap:
    environment:
      sdk: ">=3.0.0 <4.0.0"
      flutter: ">=3.0.0 <4.0.0"
    dependencies:
      collection: ^1.18.0
      flutter_flavorizr: ^2.2.2
      flutter_dotenv: ^5.1.0
    dev_dependencies:
      build_runner: ^2.3.3
      flutter_lints: ^3.0.1

      
  clean:
    hooks:
      post: |
        melos exec --flutter -- "flutter clean" 
        melos exec --flutter --file-exists="ios/Podfile.lock" -- "cd ios && rm Podfile.lock"
        melos exec --flutter --file-exists="macos/Podfile.lock" -- "cd macos && rm Podfile.lock"

  version:
    branch: main
    releaseUrl: true

# melos run ~ 
scripts:
 
  pub_get_all:
    run: flutter pub get
    description: Install all dependencies

  upgrade:
    run: |
      melos exec -- \
        "flutter pub upgrade --major-versions && flutter pub upgrade"
    description: Run upgrade the major version of the pub.
    packageFilters:
      flutter: true
      dirExists: lib

  analyze:
    run: |
      melos run analyze:dart --no-select
      melos run analyze:flutter --no-select
      melos run analyze:custom_lint --no-select
    description: Run all analyze.
    packageFilters:
      dirExists: lib

  analyze:dart:
    run: |
      melos exec -- \
        dart analyze . --fatal-infos
    description: Run analyze.
    packageFilters:
      flutter: false
      dirExists: lib

  analyze:flutter:
    run: |
      melos exec -- \
        flutter analyze . --fatal-infos
    description: Run analyze.
    packageFilters:
      flutter: true
      dirExists: lib

  analyze:custom_lint:
    run: |
      melos exec -- \
        dart run custom_lint
    description: Run custom_lint.
    packageFilters:
      dirExists: lib
      dependsOn: "custom_lint"

  format:
    run: |
      melos exec -- \
        dart format lib test
    description: Run format.
    packageFilters:
      flutter: true
      dirExists: [lib, test]
