name: model
description: A starting point for Dart libraries or applications.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
