# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false
  

      - name: install fvm
        run: |
            brew tap leoafarias/fvm
            brew install fvm

      - name: set up fvm
        run: |
          fvm install 
      - name: melos
        uses: bluefireteam/melos-action@v3

      - name: Bootstrap
        run: make bs
      
      - name: Install dependencies
         
        run: fvm dart pub global activate melos &&  melos pub_get_all
      
      - name: Setup Gradle
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/release.jks
          
      
      - name: Build APK
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        run: fvm flutter build apk --release
