# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build for iOS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa
      
      - name: Install FVM
        run: |
          curl -sL https://github.com/leoafarias/fvm/releases/latest/download/fvm_linux_amd64.tar.gz -o fvm.tar.gz
          tar -xzvf fvm.tar.gz -C ~/.local/bin
          echo 'PATH=$PATH:$HOME/.local/bin' >> $GITHUB_ENV
          source $GITHUB_ENV
      
      - name: Install Flutter version using FVM
        run: |
          source $GITHUB_ENV
          fvm install
          fvm flutter pub global activate fvm
          fvm flutter doctor
      
      - name: Bootstrap
        run: make bs
      
      - name: Install dependencies
        run: melos pub_get_all
      
      - name: Setup Gradle
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/release.jks
          
      
      - name: Build APK
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        run: fvm flutter build apk --release
