name: integrationTest
on:
  push:
    branches: ["ci"]

jobs:
  integrationTest:
    name: integration Test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17.x"
          cache: gradle
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: install fvm
        run: |
          brew tap leoafarias/fvm
          brew install fvm
  
      - name: set up fvm
        run: |
          fvm install
     
      - name:  Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - uses: 'google-github-actions/auth@v2'
        with:  
          credentials_json: '${{ secrets.FIREBASE_CREDENTIALS }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: setup google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" >> patroltest/android/app/google-services.json
      - name: Setup Gradle
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > patroltest/android/app/release.jks
      - name: Decode firebase_option

        run : echo "${{ secrets.FIREBASE_OPTION_BASE64 }}" | base64 -d > patroltest/lib/firebase_options.dart
      
      - name: Set execute project id
        run: gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}
      
      - name: Flutter tests
        run: cd patroltest && fvm flutter test
        
      - name: Generate apk for testlab
        run: |
            cd patroltest && pushd android
            fvm flutter build apk --debug
            ./gradlew app:assembleAndroidTest
            ./gradlew app:assembleDebug -Ptarget="integration_test/app_test.dart"
            popd     
      
      - name: Set execute project id
        run: gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: instrumentation tests
        run: gcloud firebase test android run --type instrumentation   --app patroltest/build/app/outputs/apk/debug/app-debug.apk   --test patroltest/build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk   --timeout 2m

        